import React from 'react'

const RootPage = () => {
    return (
        <div>
            Root-page layout
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea, iste. Expedita, sapiente laborum praesentium qui corrupti aliquid accusamus dignissimos quidem laudantium minima nisi modi, itaque veritatis. Iste quas omnis quia odit consectetur quaerat rerum vero. Neque deleniti atque sed harum culpa quas sint vitae perspiciatis hic ex qui laborum officia laboriosam earum, sit itaque maiores nihil necessitatibus, odit rem esse aut. Perspiciatis possimus quis recusandae temporibus, dolorum sit? Provident saepe dolorum maiores suscipit delectus ducimus impedit minima nobis consectetur pariatur optio distinctio, enim eius fuga nostrum obcaecati odit tempora ratione itaque! Iste quidem dicta ea accusantium quo blanditiis in perferendis cumque odio eum. Iure cupiditate iste, eum ex saepe aut repudiandae odit, provident, facilis aspernatur rerum quaerat ratione molestiae quasi placeat iusto doloribus?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea, iste. Expedita, sapiente laborum praesentium qui corrupti aliquid accusamus dignissimos quidem laudantium minima nisi modi, itaque veritatis. Iste quas omnis quia odit consectetur quaerat rerum vero. Neque deleniti atque sed harum culpa quas sint vitae perspiciatis hic ex qui laborum officia laboriosam earum, sit itaque maiores nihil necessitatibus, odit rem esse aut. Perspiciatis possimus quis recusandae temporibus, dolorum sit? Provident saepe dolorum maiores suscipit delectus ducimus impedit minima nobis consectetur pariatur optio distinctio, enim eius fuga nostrum obcaecati odit tempora ratione itaque! Iste quidem dicta ea accusantium quo blanditiis in perferendis cumque odio eum. Iure cupiditate iste, eum ex saepe aut repudiandae odit, provident, facilis aspernatur rerum quaerat ratione molestiae quasi placeat iusto doloribus?</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea, iste. Expedita, sapiente laborum praesentium qui corrupti aliquid accusamus dignissimos quidem laudantium minima nisi modi, itaque veritatis. Iste quas omnis quia odit consectetur quaerat rerum vero. Neque deleniti atque sed harum culpa quas sint vitae perspiciatis hic ex qui laborum officia laboriosam earum, sit itaque maiores nihil necessitatibus, odit rem esse aut. Perspiciatis possimus quis recusandae temporibus, dolorum sit? Provident saepe dolorum maiores suscipit delectus ducimus impedit minima nobis consectetur pariatur optio distinctio, enim eius fuga nostrum obcaecati odit tempora ratione itaque! Iste quidem dicta ea accusantium quo blanditiis in perferendis cumque odio eum. Iure cupiditate iste, eum ex saepe aut repudiandae odit, provident, facilis aspernatur rerum quaerat ratione molestiae quasi placeat iusto doloribus?</p>
        </div>
    )
}

export default RootPage
